### ISSUE TITLE
Commit ID is not always the Commit Identifier

### ISSUE THREAD

**Issue by elexis1** [elexis1/limnoria-phabricator#19]
The Phabricator plugin failed creating the following string:

> (16:26:54) WildfireRobot: I​m​a​r​o​k raised a concern with rP20492 (mauryan range and workshop) <https://code.wildfiregames.com/rP20492>

It would throw an exception and thus stop printing stories altogether:
`Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/limnoria/plugins/Phabricator/plugin.py", line 296, in printStoriesForever
    if self.printSomeStories(irc):
  File "/home/user/limnoria/plugins/Phabricator/plugin.py", line 306, in printSomeStories
    stories = self.pullSomeStories()
  File "/home/user/limnoria/plugins/Phabricator/plugin.py", line 376, in pullSomeStories
    authorName = authorName.get("data")[objectPHID]["author"]
KeyError: 'PHID-CMIT-4elvxddwhsw3wyagnfp3'
`

**Comment by elexis1** [comment]
The reason for the crash is that the plugin searches using **diffusion.querycommits** with ids = the svn commit revision ID to find the author, commit message and so forth of that commit.

However the "ids" field in Phabricator is only equal to the svn commit ID as long as only one repository exists in phabricator.

The svn commit id is still listed as "identifier", but one can't query for that.

**Comment by elexis1** [comment]
The story printing issue can be solved by querying for the commit PHIDs.

However I could not find any way to lookup commit information if only an svn commit ID is given.
This query would be needed if we want to continue printing strings about a commit if an svn commit ID is mentioned.

For instance if someone says "rP20000" in an irc channel, it did print:
> (16:11:11) WildfireRobot: rP20000 Author: e​l​e​x​i​s. Commit message: Fix some string issues and reveal the name of the next release (Ken Wood). <https://code.wildfiregames.com/rP20000>

Since there is currently no reliable way to get that information the commit reply feature must be dropped.

**Comment by elexis1** [comment]
i.e. reproduce by querying /api/diffusion.querycommits with ids = 20492 which returns Itms .gitignore commit https://code.wildfiregames.com/rFC1a52278c6f0c9ebcca37400827c1b5580fe01558 instead of LordGoods mauryan stable commit.
